#!/usr/bin/env python
import sys, string
if len(sys.argv) != 2:
  print "usage: program SYSTEM-APP"
  sys.exit(1)
tokens = string.split(sys.argv[1], '-')
program = tokens[-1]
system = string.join(tokens[0:-1], ('-'))
print "program: [%s]   system: [%s]" % (program, system)
#print tokens
#system = sys.argv[0
