set(CMAKE_SYSTEM_NAME Generic)
include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(arm-none-eabi-gcc GNU)
set(CMAKE_C_FLAGS "-g -mthumb -mcpu=cortex-m4 -ffunction-sections -fdata-sections -std=gnu99 -Wall")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "-lc -lgcc -mcpu=cortex-m4 -mthumb -static")
set(CMAKE_EXECUTABLE_SUFFIX .elf)
#set(TC arm-none-eabi-)
#set(CMAKE_LINKER ${TC}ld)
#set(CMAKE_C_COMPILER ${TC}gcc)
#set(CMAKE_FIND_LIRARY_SUFFIXES .a)
#set(CMAKE_SHARED_LIBRARIES OFF)
