set(CMAKE_SYSTEM_NAME Generic)
include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(arm-none-eabi-gcc GNU)
set(FPU_FLAGS "-mfloat-abi=hard -mfpu=fpv4-sp-d16")
set(CMAKE_C_FLAGS "-g ${FPU_FLAGS} -mthumb -mcpu=cortex-m4 -ffunction-sections -fdata-sections -std=gnu99 -Wall -DHSE_VALUE=25000000")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "-g ${FPU_FLAGS} -lc -lgcc -mcpu=cortex-m4 -mthumb -static -T ${PROJECT_SOURCE_DIR}/stm32/ld/stm32f427.ld -Wl,--no-gc-sections -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/map,--cref")
set(CMAKE_EXECUTABLE_SUFFIX .elf)
#set(TC arm-none-eabi-)
#set(CMAKE_LINKER ${TC}ld)
#set(CMAKE_C_COMPILER ${TC}gcc)
#set(CMAKE_FIND_LIRARY_SUFFIXES .a)
#set(CMAKE_SHARED_LIBRARIES OFF)
