set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER arm-none-eabi-gcc)
set(CMAKE_RANLIB CACHE STRING arm-none-eabi-ranlib)
set(CMAKE_AR CACHE STRING arm-none-eabi-ar)
#include(CMakeForceCompiler)
#CMAKE_FORCE_C_COMPILER(arm-none-eabi-gcc GNU)
set(FPU_FLAGS "-mfloat-abi=hard -mfpu=fpv4-sp-d16")
include_directories(${PROJECT_SOURCE_DIR}/systems/stm32_common/cmsis)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ffunction-sections -fdata-sections")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "-lc -lgcc -mthumb -static -Wl,--no-gc-sections -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/map,--cref")
set(CMAKE_EXECUTABLE_SUFFIX .elf)
