#set(CMAKE_SYSTEM_NAME Generic)
#include(CMakeForceCompiler)
#CMAKE_FORCE_C_COMPILER(arm-none-eabi-gcc GNU)
include(${PROJECT_SOURCE_DIR}/systems/stm32_common/cmake/stm32_common.cmake)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${FPU_FLAGS} -mcpu=cortex-m4 -mthumb -include ${STM32_CHIP_HEADER}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${FPU_FLAGS} -mcpu=cortex-m4 -T ${PROJECT_SOURCE_DIR}/systems/stm32_common/ld/stm32f746.ld")
